### ISSUE TITLE
ALGN axis vs cyrillic range for centered values

### ISSUE THREAD

**Issue by dy** [dy/wavefont#37]
\+ Both of cyrillic/latin have nice offets (0x100, 0x400)
\+ Offsets start with sequence of word 100 characters
\+ Give intuition of centered or low-bound values by C or L range names.
\+ It saves font size (somewhat)
\+ Languages sort-of use same pattern: Lowcase/upcase glyph with same original char
\+ Latin-ext is compatible with wavefont v2.
\- Data needs to be converted from 0x100 to 0x400 to be displayed under different alignment. (Sort of toUpperCase).

? Is there a case when both centered and lower bound alignment is needed?
  * Mixing waveform with spectrogram in a single line?
  * Preloaders animation (binance).
  
? Is there a case when we need to convert from one case to another?

? Is there a case when top or intermediate alignment is needed?
  * Preloaders animation (binance).

**Comment by dy** [comment]
Ok, ALGN must be an axis.

**Comment by dy** [comment]
ALGN was removed since google fonts don't have that axis, but it seems there's set of problems with Cyrillic-for-centered approach.
* Other fonts like linefont or coming tonefont don't support cyrillic range, which makes centered values non-interchangeable (linefont is very close by meaning)
* Switching back and forth from/to cyrillic range is tedious
* Reserves extra chars range unnecessarily with surrounding & clipping values
* Breaks spacing logic - chars used for spacing/breaking signal `._*-–` in latin range don't work with cyrillic range
* Center alignment must be default view, that's most expected use-case
* ALGN axis allows manual input from a-z range to be centered as well
* It expands shifts meaningfully up and down

**Comment by dy** [comment]
@RosaWagner would it make sense to use [BNCE](https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/bounce.textproto) axis or better add a new one?

**Comment by RosaWagner** [comment]
@dy the best would be for you to open issue with that question and some images and stuff in the axis registry repository directly.

**Comment by dy** [comment]
Alternatively `slnt` can be used, _-90..90_ values resemble phase plot span
![image](https://user-images.githubusercontent.com/300067/208304613-26379b62-556b-41b5-953c-481775eedab2.png)

**Comment by dy** [comment]
@RosaWagner https://github.com/googlefonts/axisregistry/issues/106

**Comment by dy** [comment]
It must be a separate axis, see arguments above.
